[package]
name = "poseidon-test-program"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers-core.workspace = true
itertools.workspace = true
poseidon-base.workspace = true
poseidon-bn254.workspace = true
sp1-zkvm.workspace = true
sp1-lib.workspace = true